services:
  php:
    build:
      context: .
    ports:
      - "8080:80"
      - "9000:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: maga_project
    ports:
      - "5432:5432"
